name: flutter_plugins_example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  path: 1.8.0-nullsafety.1
  path_provider: ^1.6.10
  device_info: 0.4.2+4
  dio: 3.0.10
  rxdart: 0.24.1
  flutter_spinkit: 4.1.2
  url_launcher: 5.5.0
  shared_preferences: 0.5.8
  get_it: 4.0.4
  get: 3.12.1
  connectivity: 0.4.9
  permission_handler: 5.0.1+1
  built_value: 7.0.4
  # 蓝牙插件
  flutter_blue: 0.7.2
  # 蓝牙插件
  flutter_ble_lib: 2.2.9
  # 蓝牙设备模拟器，仅适用于 flutter_ble_lib
  blemulator: 1.1.3
  fijkplayer: 0.8.7
  barcode_scan: 2.0.1
  qr_flutter: 3.2.0
  webview_flutter: 1.0.1
  flutter_webview_plugin: 0.3.11
  web_socket_channel: 1.1.0
  stacked: 1.7.6
  stacked_hooks: 0.1.3
  stacked_services: 0.5.4+4
  focus_detector: 1.0.3
  flare_flutter: 2.0.6
  event_bus: 1.1.1
  bot_toast: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mock data
  mockito: ^4.1.1
  injectable_generator: ^1.0.4
  build_runner: ^1.10.1
  freezed: ^0.10.9
  json_serializable: ^3.2.0
  built_value_generator: 7.0.4
  hive_generator: ^0.7.0+2
  pedantic: ^1.9.0
  logger: ^0.9.1
  analyzer: ^0.39.14

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/lang/zh.json
    - assets/lang/en.json

    - assets/animations/
    - assets/audio/viper.mp3
